name: team4_weather
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.0.1
  weather: ^3.1.1
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/
